import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import "bootstrap/dist/css/bootstrap.min.css"
import Header from "./layout/header"
import Footer from "./layout/footer"

<link
  href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=Poppins:wght@400;600;700&family=Montserrat:wght@400;700&family=Playfair+Display:wght@700&display=swap"
  rel="stylesheet"
/>;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata = {
  title: "Portfolio",
  description: "Generated by me",
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
